services:
  quiz_database:
    container_name: quiz_postgres
    image: postgres:16.1
    volumes:
      - quiz_database:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - quiz_network

  quiz_api:
    container_name: quiz_api
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - quiz_database
    networks:
      - quiz_network

volumes:
  quiz_database:

networks:
  quiz_network:
