services:
  postgres_quiz:
    container_name: postgres_quiz
    image: postgres:16.1
    volumes:
      - quiz_postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U quiz']
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '5432:5432'
    env_file:
      - '.env'
    networks:
      - quizNetwork
  
  app_quiz:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - '.env'
    ports:
     - '3000:${PORT}'
    depends_on:
      postgres_quiz:
        condition: service_started
    networks:
      - quizNetwork

volumes:
  quiz_postgres_data:

networks:
  quizNetwork:
