FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY libs/prisma/schema.prisma ./libs/prisma/schema.prisma

RUN yarn prisma:generate

EXPOSE 3000
